### ISSUE TITLE
Implementing Additional colour themes to the board

### ISSUE THREAD

**Issue by ashishpapanai** [ashishpapanai/chessJS#66]
### Allow the player to change the colour of the board from 3 colour themes? 

- [ ] Green  (#254117)+ White (#FFFFFF)
- [ ] Coffee (#6F4E37) + Blanched Almond (##FFEBCD)
- [ ] Grey  (#3D3C3A)+ White (FFFFFF)

**Additional colour themes are welcome.**

**Comment by anshuman9999** [comment]
Lmao

**Comment by ashishpapanai** [comment]
hi

**Comment by BALARAMGHOSH** [comment]
@ashishpapanai Sir, I want to contribute on this issue.

**Comment by ashishpapanai** [comment]
Hi @BALARAMGHOSH we are not closed for all frontend related enhancements till 13th January. Please refer Slack for SWOC related queries and issues assignment. 
Thank You.

**Comment by BALARAMGHOSH** [comment]
> Hi @BALARAMGHOSH we are closed for all frontend related enhancements till 13th January. Please refer Slack for SWOC related queries and issues assignment.
> Thank You.

OK, sir.
